import { somarDias } from './datas'

const haDias = (dias) => new Date(Date.now() - dias * 24 * 60 * 60 * 1000).toISOString()

export const projetosIniciais = [
  {
    id: 1,
    nome: 'TP Eng. Software',
    categoria: 'Faculdade',
    descricao: 'Sistema web de produtividade com Pomodoro, feito em equipe de quatro pessoas.',
    prazo: somarDias(12),
    status: 'ativo',
    criado_em: haDias(30),
    concluido_em: null,
  },
  {
    id: 2,
    nome: 'Cálculo II',
    categoria: 'Faculdade',
    descricao: 'Listas semanais e revisão de integrais para a segunda prova.',
    prazo: somarDias(5),
    status: 'ativo',
    criado_em: haDias(40),
    concluido_em: null,
  },
  {
    id: 3,
    nome: 'Portfólio pessoal',
    categoria: 'Pessoal',
    descricao: 'Site com projetos, currículo atualizado e links para o GitHub.',
    prazo: somarDias(45),
    status: 'ativo',
    criado_em: haDias(10),
    concluido_em: null,
  },
  {
    id: 4,
    nome: 'Inglês para proficiência',
    categoria: 'Estudos',
    descricao: 'Rotina de 30 minutos por dia até a inscrição no exame.',
    prazo: somarDias(-3),
    status: 'ativo',
    criado_em: haDias(60),
    concluido_em: null,
  },
  {
    id: 5,
    nome: 'Monitoria de Algoritmos',
    categoria: 'Trabalho',
    descricao: 'Plantões de dúvidas às quintas e correção das listas da turma.',
    prazo: null,
    status: 'ativo',
    criado_em: haDias(20),
    concluido_em: null,
  },
  {
    id: 6,
    nome: 'Sistemas Operacionais',
    categoria: 'Faculdade',
    descricao: 'Trabalho prático de escalonamento de processos.',
    prazo: somarDias(-8),
    status: 'concluido',
    criado_em: haDias(50),
    concluido_em: haDias(9),
  },
  {
    id: 7,
    nome: 'Organizar finanças',
    categoria: 'Pessoal',
    descricao: null,
    prazo: somarDias(-15),
    status: 'concluido',
    criado_em: haDias(35),
    concluido_em: haDias(16),
  },
]
